### ISSUE TITLE
WIP: Add way to delete tasks -- complete relevant tests

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-contracts#5]
Because we can't just delete something from a database on-chain and because our `/tasks` query will get very slow over time when we have thousands of tasks, we need to delete them, or at least improve the query time somehow.

- First off, we have a permanent record of Solidity `events` so if we can delete from the [task mapping](https://github.com/Distense/distense-contracts/blob/master/contracts/Tasks.sol#L31) of structs in `Tasks.sol` that would be great.  I think all we can do is set the values to 0/null/falsey values in structs.
- The way iterating works, at least in our contracts is to have an array of `taskIds` which we iterate over [_on the client_](https://github.com/Distense/distense-ui/blob/master/src/actions/tasks.js#L64) to randomly access the Solidity mapping, which is where our task data is really stored.
- So to prevent the query from getting slow, the least we can do is to remove taskIds from the `taskIds` [ array](https://github.com/Distense/distense-contracts/blob/master/contracts/Tasks.sol#L17) after some period of time, say once it's the 1000th task or when the task has been paid and it's irrelevant or perhaps some combination of both.

**Comment by JohnAllen** [comment]
WIP.  Found out deleting array indices doesn't actually shrink size of array. Have some draft code in [here](https://github.com/Distense/distense-contracts/blob/0d63145584100c2f98dd2f4d51e3afffa0b3b623/contracts/Tasks.sol#L166)

**Comment by JohnAllen** [comment]
@gilangbh here is a great first task if you're interested

**Comment by JohnAllen** [comment]
I think this is done but let's double check it

**Comment by zepcp** [comment]
What about when creating a new task, instead of adding a new element to the array, check first if we can overwrite another task that has already been completed? Just a thought..
To avoid querying the whole array looking for a task to delete, the function addTask could have another optional argument with a taskId to be deleted.. 
- If no id was sent as an argument we would just push the new task normally;
- If the id was sent, we confirm that indeed the tasks meets the requirements to be overwritten, and then we overwrite it on the array...

**Comment by JohnAllen** [comment]
I actually built this so we're good.  Gotta do a better job of marking issues as closed -- not used to having much help :)

**Comment by zepcp** [comment]
np, I saw your code and it seems good but just wanted to give you another approach..
